spring:
  application:
    name: discovery
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  server:
    renewalPercentThreshold: 0.33
    registry-sync-retries: 3
    wait-time-in-ms-when-sync-empty: 5